apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nginx-deployment
  namespace: flux-system
spec:
  interval: 1m
  path: ./clusters/aws-k3s/nginx-deployment
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: default
